cmake_minimum_required(VERSION 3.20)

project(LearnOpengl LANGUAGES C CXX)

add_subdirectory(1-openglwindow)
add_subdirectory(2-triangle)
add_subdirectory(3-texture)
add_subdirectory(4-cube)
add_subdirectory(5-camera)
add_subdirectory(6-light)
add_subdirectory(7-material)
add_subdirectory(8-LightingMaps)
add_subdirectory(9-LightCasters)
add_subdirectory(10-MultipleLights)